# Generated by Django 4.2 on 2023-05-29 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news_portal', '0003_subscription_last_notification_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='last_notification_date',
        ),
    ]
